### ISSUE TITLE
G001 - Brainstorm

### ISSUE THREAD

**Issue by edsomjr** [IJE-Suricates/Suricates#1]
Detalhes em https://github.com/edsomjr/IJE/blob/master/tasks/G001_Brainstorm.txt

**Comment by jeffersonxavier** [comment]
Professor acabamos de mandar um commit com o arquivo do Brainstorm, com algumas fotos onde rascunhamos as idéias!

**Comment by jeffersonxavier** [comment]
Professor acabamos de dar um commit com o arquivo do brainstorm, com alguns fotos onde rascunhamos as ideias para o jogo!

**Comment by edsomjr** [comment]
Caros,

não precisa colocar a sigla da issue nos nomes dos arquivos.
