### ISSUE TITLE
P003 - Janela

### ISSUE THREAD

**Issue by edsomjr** [IJE-Suricates/Suricates#10]
Detalhes em https://github.com/edsomjr/IJE/blob/master/tasks/P003_Janela.txt

**Comment by edsomjr** [comment]
Caros,

a inicialização da SDL e criação de janela são etapas de "inicialização" do jogo: logo devem estar no construtor da classe Game, e não no método run().

**Comment by edsomjr** [comment]
Caros,

o comentário anterior pode ser ignorado, uma vez que isto já foi feito no commit mais recente. Contudo, falta ainda um Makefile para poder compilar o código. Para manter a base mais organizada, seria interessante criar uma pasta com o nome do jogo e mover os diretórios src e include para lá, e criar o Makefile dentro desta nova pasta. Se quiserem um exemplo de Makefile básico, vejam o repositório da disciplina, na pasta engine.

**Comment by jeffersonxavier** [comment]
Olá Edson, acabei de dar um commit com o makefile, com relação a pasta com o nome do jogo fiquei em dúvida, o repositório já está com o nome do jogo, então já existe essa pasta, se criarmos outra ficaria algo assim: "VoidCrawlers/VoidCrawlers/..."

**Comment by edsomjr** [comment]
Jefferson,

para evitar a repetição de nomes chame esta pasta com os códigos do jogo de simplesmente de 'game'. Não vi seu commit: acho que ele foi somente local. Suba para o repositório para eu dar uma olhada no Makefile que você escreveu.

**Comment by jeffersonxavier** [comment]
Olá Edson, acabei de dar um commit com as alterações especificadas! O commit anterior tinha ido também, nós criamos uma nova branch "devel" é onde estamos comitando atualmente!

**Comment by edsomjr** [comment]
Jefferson,

confesso que passei batido e nem vi a branch. Modifiquei ligeiramente o Makefile, pois o jogo não é um teste, e adicionei o diretório bin para guardar o executável.

**Comment by jeffersonxavier** [comment]
Muito obrigado Edson, está ajudando bastante!
