### ISSUE TITLE
P004 - Módulo de Vídeo

### ISSUE THREAD

**Issue by edsomjr** [IJE-Suricates/Suricates#11]
Detalhes em https://github.com/edsomjr/IJE/blob/master/tasks/P004_Modulo_de_Video.txt

**Comment by rodrigoncalves** [comment]
Edson, qual seria o método mais apropriado para implementar as rotinas de baixo nível? Vejo apenas um método da class Game que é do tipo "virtual", que pode ser sobrescrita.

**Comment by edsomjr** [comment]
Rodrigo,

sua pergunta é justamente sua resposta: para "customizar" a classe Game via herança, é preciso adicionar métodos virtuais, que possam ser sobrescritos na classe filha (ou modifica um existente, como o draw(), por exemplo).

Contudo, os métodos de desenho em si estão mais próximas do módulo de Vídeo do que a classe Game: no Vídeo você implementa as rotinas que desenham as primitivas, na Game, você chama estas rotinas para desenhar a cena.

**Comment by rodrigoncalves** [comment]
Então para customizar a classe game é preciso que os métodos sejam virtuais. Atualmente apenas o método process_input() possui essa característica. Portanto, deve-se alterar os demais métodos para que sejam de igual modo virtuais, certo?

**Comment by edsomjr** [comment]
Rodrigo,

pode e deve. Fique a vontade para promover quaisquer alterações que julgar necessário. Nas aulas vamos discutindo as possibilidades de realização das tarefas, e o fato de ter tentado antes fortalecerá em muito o entendimento das possíveis soluções apresentadas.

**Comment by rodrigoncalves** [comment]
Ok, obrigado.

**Comment by edsomjr** [comment]
Caros,

atualizei o Makefile, para que ele utilize a biblioteca SDL_image.
