### ISSUE TITLE
G005 - Plano de Negócio

### ISSUE THREAD

**Issue by edsomjr** [IJE-Suricates/Suricates#12]
Detalhes em https://github.com/edsomjr/IJE/blob/master/tasks/G005_Plano_de_Negocio.txt

**Comment by edsomjr** [comment]
Rodrigo,

algumas observações para fecharmos esta issue:

1) Imagino que, devido a presença de sangue e cadáveres, a classificação indicativa supere os 12 anos. É importante ver as regras para classificação indicativa no Brasil e se certificar que o número é 12 mesmo.

2) Na Tabela 1, alinhe os valores em R$ à direita, centralize as quantidades e reduza a tabela para que ela não extrapole as margens do texto (use p{xcm} na primeira coluna o troque a palavra "Quantidade" por "Qtd", por exemplo).

3) Na Tabela 2 faltou o total de horas por recurso. Adicione esta coluna, tomando novamente cuidado com as margens e utilizando a formatação de colunas sugerida.

4) A Tabela 3 também ficou grande. Um modo de reduzi-la é indicar que as quantidades em milhares de reais, evitando os símbolos R$ e os zeros que sucedem a unidade de milhar. Também seria interessante aumentar um pouco a margem do documento (utilize o pacote 'geometry' para isso).

Corrigidos estes pontos poderemos encerrar esta issue.

**Comment by jeffersonxavier** [comment]
Olá professor, acabei de mandar as atualizações, com relação ao primeiro ponto estava meio equivocado a presença de sangue e cadáveres, aí deixei a mesma classificação e mudei o texto.
