### ISSUE TITLE
D002 - Versão Final do Documento de Visão

### ISSUE THREAD

**Issue by edsomjr** [IJE-Suricates/Suricates#13]
Detalhes em  https://github.com/edsomjr/IJE/blob/master/tasks/D002_Versao_Final_do_Documento_de_Visao.txt

**Comment by edsomjr** [comment]
A versão final do documento de visão deve ser um pouco mais 'visual' do que esta. Por exemplo, adicionem um mosaico/imagem no fundo, para evitar o branco, amplie as margens, faça um mosaico com os logos das tecnologias (sem necessariamente descrevê-las em bullets) e adicione uma imagem chamativa na capa.

**Comment by alexmesquita** [comment]
Professor,
O senhor pode olhar o documento de visão e ver se há algo a ser melhorado/acrescentado?

**Comment by edsomjr** [comment]
Alex,

está muito bom o documento como um todo. Eu faria apenas duas mudanças: na seção de plataformas, tiraria os textos e colocaria os logos do Windows e do Linux, lado a lado, com fundo transparente; e na descrição dos recursos tecnológicos notáveis, também tiraria os textos e colocaria o fundo da figura com o moisaico dos logos transparente.

E uma dúvida: você não tinha falado que na questão da classificação indicativa a questão da violência não seria bem esta que esta descrita (sangue, cadáveres?)

Aplique estas mudanças para encerrarmos esta issue.

**Comment by edsomjr** [comment]
Alex,

aplique estas útlimas mudanças para encerramos, e uma questão: veja com o time de vocês se posso utilizar este documento como exemplo de visão na aula de sexta-feira, que darei no Darcy, por favor.

**Comment by alexmesquita** [comment]
Professor,

Apliquei as mudanças.
Já fiz a solicitação para o restante do time, só estou esperando a resposta de todos para dar a confirmação para o senhor.

**Comment by edsomjr** [comment]
Alex,

grato pela atenção. Quando tiver a resposta favor me informar.
