### ISSUE TITLE
P006 - Tela de Apresentação

### ISSUE THREAD

**Issue by edsomjr** [IJE-Suricates/Suricates#19]
Detalhes em https://github.com/edsomjr/IJE/blob/master/tasks/P006_Tela_de_Apresentacao.txt

**Comment by alexmesquita** [comment]
Professor,
Nós fizemos essa issue na branch "devel", vamos fazer o merge pra master quando a issue "módulo de vídeo" for fechada.

**Comment by edsomjr** [comment]
Alex,

já fechei a do video. Pode fazer o merge que verifico em seguida.

**Comment by rodrigoncalves** [comment]
Merge feito.

**Comment by edsomjr** [comment]
Caros,

falta completar ainda as telas de front end, que estão descritas nas tarefas de GDD (classificação indicativa, logo da equipe, logo da SDL). Troquem as imagens 'placeholder' que eu coloquei no exemplo para as imagens apropriadas.

**Comment by edsomjr** [comment]
Jefferson,

as telas estavam fora de ordem, de acordo com o GDD (https://github.com/edsomjr/IJE/blob/master/tasks/D005_GDD_Front_End.txt), mas já mudei para a ordem certa. Só uma dúvida: o nome da equipe é Tiamat ou Tiamat Babel? Porque a primeira tela tem que ser o logo da empresa, e não do jogo: se for o caso atualize a imagem.
