### ISSUE TITLE
D001 - Versão Inicial do Documento de Visão

### ISSUE THREAD

**Issue by edsomjr** [IJE-Suricates/Suricates#3]
Detalhes em https://github.com/edsomjr/IJE/blob/master/tasks/D001_Versao_Inicial_do_Documento_de_Visao.txt

**Comment by edsomjr** [comment]
Caros,

algumas observações:

1) Na seção 'Principais Características', é detalhado o sentido vertical de exploração. Acho que ficou faltando a explicação do sentido horizontal;

2) A legenda da figura pode ficar em português, configurando o Latex com os pacotes apropriados;

3) Para encerrar, faltam apenas os logos e os recursos tecnológicos notáveis;

4) Aqui também vale a observação do corretor ortográfico, que cite no ambiente de desenvolvimento.

**Comment by alexmesquita** [comment]
Professor,

Atualizei os itens 1 e 2. Quanto ao item 3 na branch "documentation" já possui o item "recursos tecnológicos notáveis" e entendi que os logos seriam os logos desses recursos, portanto coloquei os logos neste item.
Caso não seja os logos desses itens o senhor poderia me explicar melhor o que seria?

**Comment by edsomjr** [comment]
Alex,

são os logos mesmo, mas eles devem estar "embutidos" no documento (como você fez no teclado). Quando finalizar, faça o merge com a master porque fica mais fácil para mim procurar os resultados na master do que olhar todas as diferentes branches.

**Comment by alexmesquita** [comment]
Professor,

Já fiz o merge.
