### ISSUE TITLE
G003 - Documento de Apresentação da Equipe

### ISSUE THREAD

**Issue by edsomjr** [IJE-Suricates/Suricates#5]
Detalhes em https://github.com/edsomjr/IJE/blob/master/tasks/G003_Documento_de_Apresentacao_da_Equipe.txt

**Comment by jeffersonxavier** [comment]
Olá Professor, devemos colocar informações de todos os membros inclusive os do Darcy Ribeiro, ou apenas dos alunos da FGA?

**Comment by edsomjr** [comment]
Jefferson,

é preciso colocar a equipe completa.

**Comment by jeffersonxavier** [comment]
Professor acabei de mandar um commit com o arquivo de apresentação da equipe!

**Comment by edsomjr** [comment]
Jefferson,

removi o .pdf: não precisa versionar nenhum arquivo que possa ser gerado a partir dos sources. Além disso, antes de dar um commit em um arquivo de texto utilize o aspell para checar a ortografia. O comando é

$ aspell -c -d pt_BR arquivo.txt

Se for .tex utilize também a opção -t

$ aspell -c -d pt_BR -t arquivo.tex

É preciso baixar o dicionário pt_BR. Para finalizar esta issue, mude o primeiro parágrafo "Este documento irá apresentar a equipe que estará desenvolvendo o jogo durante esse semestre." para 
"Este documento irá apresentar a equipe que estará desenvolvendo o jogo XYZ (nome provisório",
colocando o nome do jogo, mesmo que provisório. Na medida do possível, dê um aspecto profissional aos documentos, sem precisar remeter ou citar que se trata de um trabalho de uma disciplina.

**Comment by jeffersonxavier** [comment]
Documento atualizado, muito obrigado pela dica do aspell é muito bom e não conhecia!
