### ISSUE TITLE
Desenvolver o modo de navegação nas dungeons

### ISSUE THREAD

**Issue by edsomjr** [IJE-Suricates/Suricates#53]
É preciso codificar a visualização das dungeons, conforme definido pelo grupo. É preciso desenvolver um módulo que gere e armazene os mapas, e o módulo que gere a visualização a partir do mapa.

**Comment by edsomjr** [comment]
Caros,

vejam a branch dungeon_test: fiz um teste rápido em SDL1 mesmo (src/test.cpp) com o mapeamento das imagens para o modo de visão do jogo. Ainda dá para melhorar o resultado visual utilizando interpolação, mas por hora a ideia era conseguir a visualização desejada.

**Comment by edsomjr** [comment]
Caros,

fiz várias alterações no código do mapa. Agora é preciso compilar todos os .cpp da pasta teste. Falta pouco agora: 

1) o tratamento do caso especial onde uma das paredes laterais não existe;
2) converter para SDL2.

**Comment by jeffersonxavier** [comment]
Muito Obrigado pela ajuda Edson, vamos dar uma olhada!

**Comment by rodrigoncalves** [comment]
Edson, falta pouco para finalizar a tradução do código para SDL2. É preciso passar a texture recebida (imagem carregada) em Mapping::draw() para getpixel(), no entanto este último método recebe uma SDL_Surface. Além disso, é necessário chamar Canvas::update_bitmap() em algum lugar que não sabemos.

É esse mesmo o caminho?

**Comment by edsomjr** [comment]
Rodrigo,

1) como trabalharemos diretamente com pixels, as imagens devem ser carregadas como SDL_Surfaces, e não como texturas. O ideal é criar uma classe Bitmap, idêntica a classe Texture, mas que armazene uma SDL_Surface, e não uma texture, e incorporá-la no resources_manager, com um método get_bitmap() (e, e claro, finalizar com um pull request destas adições para a engine...)

2) O Canvas::update_bitmap() server para copiar o bitmap no renderer, ou seja, deve ser chamado toda vez que você finalizar o desenho do mapa (no método draw_self() da Dungeon).

**Comment by rodrigoncalves** [comment]
Professor, mesmo com as alterações ainda não foi possível concluir. Está faltando algo, que é possível que o senhor já tenha apontado. No momento, já aparece algo na tela, mas com muitos ruídos. Parece que precisa de um clear() ou algo assim.

Ainda não abri o PR com as alterações do bitmap na engine porque pode ser que ainda precise de mais alterações. De qualquer forma elas estão na branch "devel" do nosso fork.

**Comment by edsomjr** [comment]
Rodrigo,

vamos fechar isso presencialmente amanhã, daí a gente monta o PR ao final.

**Comment by rodrigoncalves** [comment]
Ok. Inclusive já tive alguns avanços. Te mostro amanhã então.

Em 19 de maio de 2015 16:58, edsomjr notifications@github.com escreveu:
